export type Workspace = { id: string; label: string; description: string };
export type ModelRouting = {
  category: "general" | "coding" | "analysis";
  model: string;
  label: string;
  reason: string;
  resource_fit: "gpu" | "hybrid_gpu_ram";
  fallback_from?: string | null;
  already_loaded?: boolean;
  switched?: boolean;
  unloaded_models?: string[];
};
export type PromptCompilation = {
  id?: string;
  original_prompt: string;
  compiled_prompt: string;
  objective: string;
  data_classification: string;
  risk_level: string;
  approvals_required?: string[];
  success_evidence?: string[];
  compiler_mode: string;
  model?: string | null;
  rewrite_duration_ms?: number;
  model_routing?: ModelRouting;
  created_at?: string;
};
export type Project = {
  id: string;
  name: string;
  description: string;
  root_path: string;
  repository_url?: string | null;
  status: string;
  task_count?: number;
  tasks?: Task[];
  updated_at: string;
};
export type Task = {
  id: string;
  project_id: string;
  title: string;
  prompt: string;
  status: string;
  risk_level: string;
  assigned_agent?: string | null;
  result_summary?: string | null;
  prompt_compilation?: PromptCompilation | null;
  updated_at: string;
};
export type ConversationMessage = {
  id: string;
  conversation_id: string;
  task_id?: string | null;
  role: "user" | "assistant";
  content: string;
  provider?: string | null;
  model?: string | null;
  token_count: number;
  compilation?: PromptCompilation | null;
  error?: string | null;
  created_at: string;
  streaming?: boolean;
};
export type Conversation = {
  id: string;
  project_id: string;
  title: string;
  status: "active" | "archived";
  created_at: string;
  updated_at: string;
  last_message_at?: string | null;
  message_count: number;
  preview?: string;
  encrypted_at_rest: boolean;
  messages?: ConversationMessage[];
};
export type Agent = {
  id: string;
  name: string;
  role: string;
  description: string;
  model_policy: string;
  status: string;
  prompt_version: string;
  capabilities: string[];
  skills: Array<{ id: string; name: string; category: string; version: string; status: string }>;
};
export type Skill = {
  id: string;
  name: string;
  category: string;
  description: string;
  version: string;
  status: string;
  risk_level: string;
  capabilities: string[];
};
export type Plugin = {
  id: string;
  name: string;
  category: string;
  description: string;
  status: string;
  connection_status: string;
  requires_approval: boolean;
  data_policy: string;
  capabilities: string[];
};
export type Approval = {
  id: string;
  action: string;
  summary: string;
  risk_level: string;
  status: string;
  evidence: Record<string, unknown>;
  execution?: { status: "running" | "completed" | "failed"; result_summary: string; started_at: string; finished_at?: string | null } | null;
  requested_at: string;
};
export type Activity = {
  id: number;
  event_type: string;
  summary: string;
  security_level: string;
  created_at: string;
};
export type WorldPulseItem = {
  headline: string;
  summary: string;
  source_url?: string | null;
  domain?: string | null;
  confidence: number;
  verification_state: string;
};
export type ResearchReport = {
  id: string;
  project_id?: string | null;
  purpose: "world_pulse" | "opportunity";
  query: string;
  title: string;
  status: string;
  source_count: number;
  independent_domains: number;
  created_at: string;
  report: {
    title: string;
    generated_at: string;
    classification: string;
    decision_state: string;
    quality_gate?: string;
    executive_summary: string[];
    key_findings: Array<{ headline: string; evidence: string; source_ids: string[]; confidence: number; implication: string }>;
    claim_assessments?: Array<{ id: string; claim: string; status: "corroborated" | "needs_reconciliation" | "single_source"; source_ids: string[]; independent_domains: string[]; metric_values: string[]; confidence: number }>;
    recommended_next_steps: string[];
    further_questions: string[];
    caveats: string[];
    source_metrics: Record<string, unknown>;
    sources: Array<{ id: string; title: string; url: string; domain: string; source_tier: string; verification_state: string; confidence: number; published_at?: string | null; freshness_state?: string; page_verification_state?: string; date_source?: string | null; methodology_terms?: string[] }>;
  };
};
export type GitHubStatus = {
  installed: boolean;
  authenticated?: boolean | null;
  remote_verification: string;
  repository_url?: string | null;
  git?: {
    available: boolean;
    branch: string;
    clean: boolean;
    origin_matches_registered: boolean;
  };
};
export type GitHubAction = "verify_auth" | "create_branch" | "stage_files" | "commit" | "push" | "draft_pr";
export type CodexStatus = {
  installed: boolean;
  connected: boolean;
  authenticated?: boolean;
  protocol: string;
  account_type?: string | null;
  plan_type?: string | null;
  requires_openai_auth?: boolean;
  error?: string;
};
export type Bootstrap = {
  brand: { name: string; descriptor: string; motto: string; creed: string };
  workspaces: Workspace[];
  overview: {
    projects: number;
    agents: number;
    pending_approvals: number;
    open_tasks: number;
    opportunity_allocation: { existing: number; exploration: number };
  };
  projects: Project[];
  conversations: Conversation[];
  agents: Agent[];
  skills: Skill[];
  plugins: Plugin[];
  approvals: Approval[];
  world_pulse: WorldPulseItem[];
  research_reports: ResearchReport[];
  opportunities: Array<Record<string, unknown>>;
  solutions: Array<Record<string, unknown>>;
  activity: Activity[];
  foundation: Record<string, unknown>;
  local_model: {
    available: boolean;
    model: string;
    endpoint: string;
    loaded?: boolean;
    gpu_accelerated?: boolean;
    size_vram?: number;
    routing_enabled?: boolean;
    one_model_at_a_time?: boolean;
    active_models?: string[];
    routes?: Record<string, { model: string; label: string; installed: boolean; resource_fit: string }>;
    error?: string;
  };
  integrations: { github: GitHubStatus; codex: CodexStatus };
};
