export type Workspace = { id: string; label: string; description: string };
export type ModelRouting = {
  category: "general" | "coding" | "analysis" | "vision";
  model: string;
  label: string;
  reason: string;
  resource_fit: "gpu" | "hybrid_gpu_ram";
  fallback_from?: string | null;
  already_loaded?: boolean;
  switched?: boolean;
  unloaded_models?: string[];
};
export type PromptCompilation = {
  id?: string;
  original_prompt: string;
  compiled_prompt: string;
  objective: string;
  data_classification: string;
  risk_level: string;
  approvals_required?: string[];
  success_evidence?: string[];
  compiler_mode: string;
  model?: string | null;
  rewrite_duration_ms?: number;
  model_routing?: ModelRouting;
  created_at?: string;
};
export type Project = {
  id: string;
  name: string;
  description: string;
  root_path: string;
  repository_url?: string | null;
  status: string;
  task_count?: number;
  tasks?: Task[];
  updated_at: string;
};
export type Task = {
  id: string;
  project_id: string;
  title: string;
  prompt: string;
  status: string;
  risk_level: string;
  assigned_agent?: string | null;
  result_summary?: string | null;
  prompt_compilation?: PromptCompilation | null;
  updated_at: string;
};
export type ConversationMessage = {
  id: string;
  conversation_id: string;
  task_id?: string | null;
  role: "user" | "assistant";
  content: string;
  provider?: string | null;
  model?: string | null;
  token_count: number;
  compilation?: PromptCompilation | null;
  error?: string | null;
  created_at: string;
  streaming?: boolean;
  ephemeral?: boolean;
};
export type Conversation = {
  id: string;
  project_id: string;
  title: string;
  status: "active" | "archived";
  created_at: string;
  updated_at: string;
  last_message_at?: string | null;
  message_count: number;
  preview?: string;
  encrypted_at_rest: boolean;
  messages?: ConversationMessage[];
};
export type Agent = {
  id: string;
  name: string;
  role: string;
  description: string;
  model_policy: string;
  status: string;
  prompt_version: string;
  capabilities: string[];
  skills: Array<{ id: string; name: string; category: string; version: string; status: string }>;
};
export type IndependentAgent = Agent & {
  bridge: {
    url: string;
    dashboard_url?: string | null;
    enabled: boolean;
    contract_version: string;
    last_seen_at?: string | null;
    last_status: string;
    last_error?: string | null;
  };
  snapshot: {
    observed_at?: string;
    identity?: { agent_id: string; display_name?: string; agent_version?: string; capabilities?: string[] };
    health?: { status?: string; state?: string; observed_at?: string; checks?: Array<Record<string, unknown>> };
    metrics?: {
      tasks_total?: number;
      tasks_by_status?: Record<string, number>;
      failure_rate?: number;
      success_rate?: number;
      average_duration_ms?: number;
      last_success_at?: string | null;
      last_failure_at?: string | null;
      domain?: Record<string, number>;
      resources?: { cpu_percent?: number; memory_percent?: number; rss_mb?: number };
    };
    tasks?: Array<{ task_id: string; task_type: string; status: string; created_at?: string; updated_at?: string }>;
    approvals?: Array<Record<string, unknown>>;
    security_events?: Array<Record<string, unknown>>;
    skills?: Array<Record<string, unknown>>;
    controls?: { quarantined?: boolean; quarantine_reason?: string | null; paused_capabilities?: string[]; updated_at?: string };
    learning?: Array<Record<string, unknown>>;
  };
  open_incidents: number;
};
export type AgentIncident = {
  id: string;
  agent_id: string;
  severity: "low" | "medium" | "high" | "critical";
  incident_type: string;
  title: string;
  status: "open" | "contained" | "resolved";
  capability?: string | null;
  report: {
    summary?: string;
    evidence?: Record<string, unknown>;
    action_taken?: Record<string, unknown>;
    possible_solutions?: string[];
    recovery_steps?: string[];
    notification_state?: string;
    phone_notification_state?: string;
  };
  detected_at: string;
  resolved_at?: string | null;
};
export type AgentControl = {
  id: string;
  agent_id: string;
  action: string;
  capability?: string | null;
  reason: string;
  source: "automatic" | "owner";
  outcome: string;
  details: Record<string, unknown>;
  created_at: string;
};
export type AgentLearningUpdate = {
  id: string;
  agent_id: string;
  course_id?: string | null;
  title: string;
  source: string;
  content_sha256: string;
  content_preview: string;
  risk_level: string;
  status: string;
  evaluation: Record<string, unknown>;
  deployment: Record<string, unknown>;
  created_at: string;
  deployed_at?: string | null;
};
export type Skill = {
  id: string;
  name: string;
  category: string;
  description: string;
  version: string;
  status: string;
  risk_level: string;
  capabilities: string[];
};
export type Plugin = {
  id: string;
  name: string;
  category: string;
  description: string;
  status: string;
  connection_status: string;
  requires_approval: boolean;
  data_policy: string;
  capabilities: string[];
};
export type Approval = {
  id: string;
  action: string;
  approval_queue: "security_operations" | "business_creative";
  summary: string;
  risk_level: string;
  status: string;
  evidence: Record<string, unknown>;
  execution?: { status: "running" | "completed" | "failed"; result_summary: string; started_at: string; finished_at?: string | null } | null;
  requested_at: string;
};
export type Activity = {
  id: number;
  event_type: string;
  summary: string;
  security_level: string;
  created_at: string;
};
export type WorldPulseItem = {
  id?: string;
  region?: string;
  category?: string;
  headline: string;
  summary: string;
  source_url?: string | null;
  domain?: string | null;
  confidence: number;
  verification_state: string;
  published_at?: string | null;
  collected_at?: string;
  retrieved_at?: string;
};
export type AcademyCourse = {
  id: string;
  title: string;
  provider: string;
  source_url?: string | null;
  status: "planned" | "active" | "completed" | "paused";
  progress: number;
  learning_goal: string;
  updated_at: string;
  completion_ready: boolean;
  materials: Array<{ id: string; module_title: string; source_url?: string | null; content_sha256: string; verification_state: string; created_at: string }>;
  assessments: Array<{ id: string; title: string; assessment_type: string; score: number; passed: boolean; evidence: Record<string, unknown>; created_at: string }>;
};
export type LearningMemory = {
  id: string;
  kind: "explicit" | "inferred";
  category: string;
  statement: string;
  reason: string;
  confidence: number;
  status: "proposed" | "confirmed" | "disabled";
  affects_authority: boolean;
};
export type WorldPulseSourceCandidate = {
  id: string;
  label: string;
  niche: string;
  source_type: "publisher" | "public_account" | "public_data";
  locator: string;
  reason: string;
  identity_verified: boolean;
  status: string;
  approval_status: string;
};
export type WorldPulseSchedule = {
  id: string;
  name: string;
  niche: string;
  query: string;
  cadence_hours: number;
  execution_policy: "approval_each_run";
  status: "planned" | "paused";
  last_requested_at?: string | null;
};
export type ResponseFeedback = {
  id: string;
  message_id: string;
  rating: "helpful" | "too_generic" | "incorrect" | "missed_intent";
  correction: string;
  created_at: string;
  updated_at: string;
};
export type TrainingCandidate = {
  id: string;
  feedback_id: string;
  conversation_id: string;
  prompt_excerpt: string;
  response_excerpt: string;
  correction: string;
  rating: string;
  status: "proposed" | "approved" | "rejected";
  created_at: string;
  decided_at?: string | null;
};
export type IdentityProfile = {
  id: string;
  display_name: string;
  role_title: string;
  pronouns: string;
  embodiment: "always_digital";
  conversation_style: "professional_warm" | "concise_executive" | "collaborative_deep_dive";
  presentation_mode: "executive" | "study" | "studio" | "public_incognito";
  traits: string[];
  truth_standard: "strict";
  authority_model: "owner_controlled";
  identity_disclosure: string;
  authority_boundary: Record<string, boolean>;
};
export type IdentityAsset = {
  id: string;
  asset_type: "portrait" | "full_body" | "voice" | "motion_rig";
  label: string;
  public_path?: string | null;
  content_sha256?: string | null;
  status: "active" | "reference" | "planned" | "disabled";
  identity_locked: boolean;
};
export type CompanionSession = {
  id: string;
  project_id?: string | null;
  session_type: "study" | "task" | "research" | "creative";
  privacy_mode: "standard" | "private_incognito";
  screen_access: "none" | "local_preview";
  retention_policy: "notes_only" | "metadata_only";
  purpose: string;
  status: "active" | "completed" | "aborted";
  summary: string;
  started_at: string;
  ended_at?: string | null;
  notes: Array<{ id: string; author: "owner" | "aegis"; content: string; learning_candidate: boolean; created_at: string }>;
};
export type DigitalIdentity = {
  profile: IdentityProfile;
  assets: IdentityAsset[];
  companion_sessions: CompanionSession[];
  modes: Record<string, string>;
  screen_companion: {
    available: boolean;
    capture_boundary: string;
    frame_destination: string;
    recording: boolean;
    automatic_visual_analysis: boolean;
    notes: string;
    model?: string;
    raw_frame_retention?: string;
    transport?: string;
    error?: string;
  };
  production_readiness: Record<string, string>;
};
export type OpportunityCycle = {
  id: string;
  name: string;
  niche: string;
  query: string;
  allocation: "existing-80" | "explore-20";
  cadence_hours: number;
  status: "active" | "paused";
  last_run_at?: string | null;
};
export type ContainmentDrill = {
  id: string;
  agent_id: string;
  status: "running" | "passed" | "failed";
  report: Record<string, unknown>;
  created_at: string;
  completed_at?: string | null;
};
export type ResearchReport = {
  id: string;
  project_id?: string | null;
  purpose: "world_pulse" | "opportunity";
  query: string;
  title: string;
  status: string;
  source_count: number;
  independent_domains: number;
  created_at: string;
  report: {
    title: string;
    generated_at: string;
    classification: string;
    decision_state: string;
    quality_gate?: string;
    executive_summary: string[];
    key_findings: Array<{ headline: string; evidence: string; source_ids: string[]; confidence: number; implication: string }>;
    claim_assessments?: Array<{ id: string; claim: string; status: "corroborated" | "needs_reconciliation" | "single_source"; source_ids: string[]; independent_domains: string[]; metric_values: string[]; confidence: number }>;
    recommended_next_steps: string[];
    further_questions: string[];
    caveats: string[];
    source_metrics: Record<string, unknown>;
    sources: Array<{ id: string; title: string; url: string; domain: string; source_tier: string; verification_state: string; confidence: number; published_at?: string | null; freshness_state?: string; page_verification_state?: string; date_source?: string | null; methodology_terms?: string[] }>;
  };
};
export type GitHubStatus = {
  installed: boolean;
  authenticated?: boolean | null;
  remote_verification: string;
  repository_url?: string | null;
  git?: {
    available: boolean;
    branch: string;
    clean: boolean;
    origin_matches_registered: boolean;
  };
};
export type GitHubAction = "verify_auth" | "inspect_governance" | "create_branch" | "stage_files" | "commit" | "push" | "draft_pr";
export type GitHubGovernance = {
  repository: string;
  base_branch: string;
  current_branch: string;
  protection: {
    state: string;
    required_checks: string[];
    required_check_integrations: string[];
    strict_checks?: boolean;
    required_approving_reviews: number;
    dismiss_stale_reviews?: boolean;
    enforce_admins?: boolean;
    restrictions_enabled?: boolean;
  };
  pull_request: {
    found: boolean;
    number?: number;
    url?: string;
    is_draft?: boolean;
    review_decision?: string;
    merge_state?: string;
    checks?: Array<{ name: string; state: string }>;
    checks_total?: number;
    checks_failing?: number;
    checks_pending?: number;
    reason?: string;
  };
};
export type SecurityScan = {
  project_id: string;
  project_name: string;
  mode: "local_static_read_only";
  network_used: false;
  file_source: string;
  files_considered: number;
  files_scanned: number;
  files_skipped: number;
  finding_limit_reached: boolean;
  status: "passed" | "attention" | "critical";
  counts: Record<"critical" | "high" | "medium" | "low", number>;
  findings: Array<{ severity: string; rule: string; file: string; line?: number | null; message: string }>;
  dependency_posture: Record<string, string | number | null>;
  limitations: string[];
};
export type CodexStatus = {
  installed: boolean;
  connected: boolean;
  authenticated?: boolean;
  protocol: string;
  account_type?: string | null;
  plan_type?: string | null;
  requires_openai_auth?: boolean;
  error?: string;
};
export type Bootstrap = {
  brand: { name: string; descriptor: string; motto: string; creed: string };
  workspaces: Workspace[];
  overview: {
    projects: number;
    agents: number;
    pending_approvals: number;
    open_tasks: number;
    opportunity_allocation: { existing: number; exploration: number };
  };
  projects: Project[];
  conversations: Conversation[];
  agents: Agent[];
  agent_fleet: IndependentAgent[];
  agent_incidents: AgentIncident[];
  agent_controls: AgentControl[];
  agent_learning_updates: AgentLearningUpdate[];
  skills: Skill[];
  plugins: Plugin[];
  approvals: Approval[];
  world_pulse: WorldPulseItem[];
  world_pulse_sources: WorldPulseSourceCandidate[];
  world_pulse_schedules: WorldPulseSchedule[];
  opportunity_cycles: OpportunityCycle[];
  research_reports: ResearchReport[];
  opportunities: Array<Record<string, unknown>>;
  solutions: Array<Record<string, unknown>>;
  academy_courses: AcademyCourse[];
  containment_drills: ContainmentDrill[];
  learning_memory: LearningMemory[];
  response_feedback: ResponseFeedback[];
  training_candidates: TrainingCandidate[];
  digital_identity: DigitalIdentity;
  operations: {
    backup_count: number;
    latest_backup?: string | null;
    latest_backup_bytes: number;
    encrypted_only: boolean;
    restore_policy: string;
    production_restore: string;
    startup_launcher: string;
  };
  voice: {
    transcription_available: boolean;
    speech_available: boolean;
    session_state: string;
    interrupt_available: boolean;
    raw_audio_retention: string;
    transcript_retention: string;
  };
  activity: Activity[];
  foundation: Record<string, unknown>;
  local_model: {
    available: boolean;
    model: string;
    endpoint: string;
    loaded?: boolean;
    gpu_accelerated?: boolean;
    size_vram?: number;
    routing_enabled?: boolean;
    one_model_at_a_time?: boolean;
    active_models?: string[];
    routes?: Record<string, { model: string; label: string; installed: boolean; resource_fit: string }>;
    error?: string;
  };
  integrations: { github: GitHubStatus; codex: CodexStatus };
};
